package main

// Common constants consolidated to avoid repeated string literals across CLI commands (go:S1192).
const (
	// Output formatting
	flagOutputFormatDesc = "Output format: table or json"
	flagFullIDDesc       = "Show full UUIDs in table output"
	formatConfigRow      = "%-34s %s\n"
	valNotSet            = "(not set)"
	headerDueDate        = "DUE DATE"
	headerStartDate      = "START DATE"

	// Common CLI Flag names
	flagFullID                          = "full-id"
	flagRuntimeID                       = "runtime-id"
	flagRuntimeConfig                   = "runtime-config"
	flagThinkingLevel                   = "thinking-level"
	flagServiceTier                     = "service-tier"
	flagCustomArgs                      = "custom-args"
	flagCustomEnv                       = "custom-env"
	flagCustomEnvStdin                  = "custom-env-stdin"
	flagCustomEnvFile                   = "custom-env-file"
	flagMCPConfig                       = "mcp-config"
	flagPermissionMode                  = "permission-mode"
	flagPublicToWorkspace               = "public-to-workspace"
	flagPublicToMember                  = "public-to-member"
	flagMaxConcurrentTasks              = "max-concurrent-tasks"
	flagSkillIDs                        = "skill-ids"
	flagDaemonID                        = "daemon-id"
	flagDeviceName                      = "device-name"
	flagRuntimeName                     = "runtime-name"
	flagWorkspacesRoot                  = "workspaces-root"
	flagPollInterval                    = "poll-interval"
	flagHeartbeatInterval               = "heartbeat-interval"
	flagAgentTimeout                    = "agent-timeout"
	flagCodexSemanticInactivityTimeout = "codex-semantic-inactivity-timeout"
	flagCodexHandshakeTimeout           = "codex-handshake-timeout"
	flagNoAutoUpdate                    = "no-auto-update"
	flagAutoUpdateInterval              = "auto-update-interval"
	flagNoAutoReload                    = "no-auto-reload"
	flagAllowExternalFile               = "allow-external-file"
	flagAssigneeID                      = "assignee-id"
	flagDescriptionStdin                = "description-stdin"
	flagDescriptionFile                 = "description-file"
	flagStartDate                       = "start-date"
	flagDueDate                         = "due-date"
	flagNoStart                         = "no-start"
	flagUserID                          = "user-id"
	flagDefaultBranchHint               = "default-branch-hint"
	flagLocalPath                       = "local-path"
	flagRefLabel                        = "ref-label"
	flagExecutionMode                   = "execution-mode"
	flagAvatarURL                       = "avatar-url"
	flagMemberID                        = "member-id"
	flagContextStdin                    = "context-stdin"
	flagIssuePrefix                     = "issue-prefix"
	flagServerConfig                    = "server-config"
	flagIssueTitleTemplate              = "issue-title-template"
	flagContentStdin                    = "content-stdin"
	flagContentFile                     = "content-file"
	flagCommandName                     = "command-name"
	flagDisplayName                     = "display-name"
	flagFrontendPort                    = "frontend-port"

	// Common API Endpoints
	apiAgentsPrefix     = "/api/agents/"
	apiAutopilotsPrefix = "/api/autopilots/"
	apiIssuesPrefix     = "/api/issues/"
	apiLabelsPrefix     = "/api/labels/"
	apiMe               = "/api/me"
	apiProjectsPrefix   = "/api/projects/"
	apiRuntimesPrefix   = "/api/runtimes/"
	apiSkillsPrefix     = "/api/skills/"
	apiSquadsPrefix     = "/api/squads/"
	apiWorkspacesPrefix = "/api/workspaces/"
	pathLabels          = "/labels"
	pathMembers         = "/members"
	pathMetadata        = "/metadata"
	pathResources       = "/resources"
	pathTriggers        = "/triggers/"

	// Common network bindings & messages
	bindAllIPv4            = "0.0.0.0"
	hintMulticaLogin       = "multica login"
	descMemberOrAgentID    = "Member or agent ID (required)"
	descMemberType         = "Member type: agent or member"
	descMetadataKey        = "Metadata key (required)"
	formatServerURL        = "  server_url: %s\n"
	formatAppURL           = "  app_url:    %s\n"
	errResolveAssignee     = "resolve assignee: %w"
	errResolveAutopilot    = "resolve autopilot: %w"
	errResolveIssue        = "resolve issue: %w"
	errResolveLabel        = "resolve label: %w"
	errResolveProject      = "resolve project: %w"
	errResolveTrigger      = "resolve trigger: %w"
	errFailedToSaveConfig  = "failed to save config: %w"
	errKeyRequired         = "--key is required"
	errMemberIDRequired    = "--member-id is required"
	errNameRequired        = "--name is required"
	errWorkspaceIDRequired = "workspace ID is required: pass an id/slug/prefix as argument or set MULTICA_WORKSPACE_ID"
)
