package handler

// Common constants consolidated to avoid repeated string literals across handlers (go:S1192).
const (
	// Common HTTP Errors & Messages
	errMsgInvalidRequestBody             = "invalid request body"
	errMsgWorkspaceNotFound              = "workspace not found"
	errMsgInsufficientPermissions        = "insufficient permissions"
	errMsgInternalError                  = "internal error"
	errMsgNotFound                       = "not found"
	errMsgInvalidCursor                  = "invalid cursor"
	errMsgFailedToStartTx                = "failed to start transaction"
	errMsgFailedToCommit                 = "failed to commit"
	errMsgUserNotFound                   = "user not found"
	errMsgTaskNotFound                   = "task not found"
	errMsgRuntimeNotFound                = "runtime not found"
	errMsgIssueNotFound                  = "issue not found"
	errMsgCommentNotFound                = "comment not found"
	errMsgProjectNotFound                = "project not found"
	errMsgLabelNotFound                  = "label not found"
	errMsgSkillNotFound                  = "skill not found"
	errMsgAutopilotNotFound              = "autopilot not found"
	errMsgTriggerNotFound                = "trigger not found"
	errMsgInvitationNotFound             = "invitation not found"
	errMsgPropertyNotFound               = "property not found"
	errMsgMCPServerNotFound              = "MCP server not found"
	errMsgRuntimeProfileNotFound         = "runtime profile not found"
	errMsgAttachmentNotFound             = "attachment not found"
	errMsgWebhookNotFound                = "webhook not found"
	errMsgRequestNotFound                = "request not found"
	errMsgProjectResourceNotFound        = "project resource not found"
	errMsgAgentBuilderSessionNotFound    = "agent builder session not found"
	errMsgAgentNotFoundInWorkspace       = "agent not found in this workspace"
	errMsgParentIssueNotFoundInWorkspace = "parent issue not found in this workspace"
	errMsgProjectNotFoundInWorkspace     = "project not found in this workspace"
	errMsgTargetUserNotMember            = "target user is not a member of this workspace"
	errMsgNoAccessToAgent                = "you do not have access to this agent"
	errMsgWorkspaceMustHaveOwner         = "workspace must have at least one owner"
	errMsgWorkspaceIDRequired            = "workspace_id is required"
	errMsgLabelIDRequired                = "label_id is required"
	errMsgAssigneeTypeMustBe             = "assignee_type must be agent or squad"
	errMsgSkillAlreadyExists             = "a skill with this name already exists"
	errMsgInvitationNotYours             = "invitation does not belong to you"
	errMsgChatAgentArchived              = "chat agent is archived"
	errMsgChatSessionArchived            = "chat session is archived"
	errMsgChatBindingReadFailed          = "chat session channel binding read failed"
	errMsgComposioNotConfigured          = "composio integration not configured"
	errMsgDingtalkNotConfigured          = "dingtalk integration not configured"
	errMsgWecomNotEnabled                = "wecom integration not enabled"
	errMsgFailedToResolveAgentAccess     = "failed to resolve agent access"
	errMsgFailedToLoadAgentSkills        = "failed to load agent skills"
	errMsgFailedToSaveAgentDraft         = "failed to save agent builder draft"
	errMsgFailedToUpdateEnv              = "failed to update env"
	errMsgFailedToGenerateToken          = "failed to generate token"
	errMsgFailedToCreateAutopilot        = "failed to create autopilot"
	errMsgFailedToUpdateAutopilot        = "failed to update autopilot"
	errMsgFailedToDeleteAutopilot        = "failed to delete autopilot"
	errMsgFailedToCreateTrigger          = "failed to create trigger"
	errMsgFailedToUpdateTrigger          = "failed to update trigger"
	errMsgFailedToDeleteTrigger          = "failed to delete trigger"
	errMsgFailedToAcceptInvitation       = "failed to accept invitation"
	errMsgFailedToAddMCPServer           = "failed to add the MCP server"
	errMsgFailedToArchiveIssueStatus     = "failed to archive issue status"
	errMsgFailedToAuthPluginCall         = "failed to authorize the Plugin call"
	errMsgFailedToCreateOnboardingIssue  = "failed to create onboarding issue"
	errMsgFailedToCreateShareLink        = "failed to create share link"
	errMsgFailedToCreateMCPServer        = "failed to create the MCP server"
	errMsgFailedToDeleteRuntime          = "failed to delete runtime"
	errMsgFailedToDeleteMCPServer        = "failed to delete the MCP server"
	errMsgFailedToDeleteWorkspace        = "failed to delete workspace"
	errMsgFailedToListGroupedIssues      = "failed to list grouped issues"
	errMsgFailedToListIssues             = "failed to list issues"
	errMsgFailedToListTableFacets        = "failed to list table facets"
	errMsgFailedToListTableGroups        = "failed to list table groups"
	errMsgFailedToListTableRows          = "failed to list table rows"
	errMsgFailedToLoadRequest            = "failed to load request: "
	errMsgFailedToLoadSquadMemberPreview = "failed to load squad member preview"
	errMsgFailedToLoadUser               = "failed to load user"
	errMsgFailedToReadFile               = "failed to read file"
	errMsgFailedToRecordClientUsage      = "failed to record client usage"
	errMsgFailedToReorderIssueStatuses   = "failed to reorder issue statuses"
	errMsgFailedToResolveComment         = "failed to resolve comment"
	errMsgFailedToResolveTableGroup      = "failed to resolve table group"
	errMsgFailedToUpdateChatSession      = "failed to update chat session"
	errMsgFailedToUpdateRuntime          = "failed to update runtime"
	errMsgFailedToUpdateSquad            = "failed to update squad"
	errMsgInvalidDueDateFormat           = "invalid due_date format, expected YYYY-MM-DD"
	errMsgInvalidGroupKey                = "invalid group_key"
	errMsgInvalidSortValue               = "invalid sort value"
	errMsgLocalSkillImportFail           = "local skill import Fail failed"
	errMsgPinSessionFailed               = "pin session failed"

	// Common URL parameter & attribute keys
	paramWorkspaceID   = "workspace id"
	paramUserID        = "user id"
	paramAutopilotID   = "autopilot id"
	paramTriggerID     = "trigger id"
	paramAttachmentID  = "attachment id"
	paramCommentID     = "comment id"
	paramInvitationID  = "invitation id"
	paramLabelID       = "label id"
	paramProfileID     = "profile id"
	paramProjectID     = "project id"
	paramPropertyID    = "property id"
	paramQuickActionID = "quick action id"
	paramServerID      = "server id"

	// HTTP Headers & Media Types
	headerContentLength   = "Content-Length"
	headerContentType     = "Content-Type"
	headerXGitHubDelivery = "X-GitHub-Delivery"
	headerXRequestID      = "X-Request-ID"
	mimeAppJavascript     = "application/javascript"

	// Layouts, Paths & URLs
	dateLayoutISO          = "2006-01-02"
	pathAPIV1Nodes         = "/api/v1/nodes"
	pathAPIV1Subscriptions = "/api/v1/subscriptions/"
	urlSSOFailed           = "/login?error=sso_failed"

	// SQL Expressions & Column Names
	sqlAssigneeMatch      = "(i.assignee_type = %s::text AND i.assignee_id = %s::uuid)"
	sqlAssigneeNull       = "(i.assignee_type IS NULL AND i.assignee_id IS NULL)"
	sqlLikeLowerTitle     = "LOWER(i.title) LIKE %s"
	sqlNumberEq           = "i.number = %s"
	sqlStatusAny          = "i.status = ANY(%s::text[])"
	sqlStatusCol          = "i.status"
	sqlPositionCol        = "i.position"
	sqlLikeWildcardSuffix = " || '%'"

	// Miscellaneous string literals
	fileSkillMD            = "SKILL.md"
	fileSkillMDLower       = "skill.md"
	pathSkillMD            = "/SKILL.md"
	formatHTTPStatus       = "HTTP %d"
	prefixInvalid          = "invalid "
	errFmtInvalidURL       = "invalid URL: %w"
	errFmtMarshalListReq   = "marshal list request: %w"
	prefixResourcesBracket = "resources["
	prefixUnset            = "unset:"
)
